-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.7
-- Sat Feb 22 16:53:14 2025

-- parameterized module component declaration
component pll_gen
    port (CLKI: in  std_logic; RST: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic; 
        CLKOS3: out  std_logic; LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll_gen
    port map (CLKI=>__, RST=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__, 
        CLKOS3=>__, LOCK=>__);
