-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 5.8
-- Thu Feb 13 08:58:32 2025

-- parameterized module component declaration
component dcfifo_tx_b2
    port (Data: in  std_logic_vector(9 downto 0); WrClock: in  std_logic; 
        RdClock: in  std_logic; WrEn: in  std_logic; RdEn: in  std_logic; 
        Reset: in  std_logic; RPReset: in  std_logic; 
        Q: out  std_logic_vector(9 downto 0); Empty: out  std_logic; 
        Full: out  std_logic);
end component;

-- parameterized module component instance
__ : dcfifo_tx_b2
    port map (Data(9 downto 0)=>__, WrClock=>__, RdClock=>__, WrEn=>__, 
        RdEn=>__, Reset=>__, RPReset=>__, Q(9 downto 0)=>__, Empty=>__, 
        Full=>__);
