[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 16;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = slv_com_top_inst.CLKCOM_OUT;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 172;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = slv_com_top_inst/CLK2A;
GLOBAL_PRIMARY_1_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_1_LOADNUM = 16;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = s_PLL_CLK20M;
GLOBAL_PRIMARY_2_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_2_LOADNUM = 5186;
; Global primary clock #3
GLOBAL_PRIMARY_3_SIGNALNAME = slv_com_top_inst.CLK1;
GLOBAL_PRIMARY_3_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_3_LOADNUM = 333;
; Global primary clock #4
GLOBAL_PRIMARY_4_SIGNALNAME = CLK20M_c;
GLOBAL_PRIMARY_4_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_4_LOADNUM = 9;
; Global primary clock #5
GLOBAL_PRIMARY_5_SIGNALNAME = TX_RSTb_i_o3;
GLOBAL_PRIMARY_5_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_5_LOADNUM = 0;
; Global primary clock #6
GLOBAL_PRIMARY_6_SIGNALNAME = stm12/ppmc_reg_S118M_inst/nMRST_i_1;
GLOBAL_PRIMARY_6_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_6_LOADNUM = 0;
; Global primary clock #7
GLOBAL_PRIMARY_7_SIGNALNAME = stm02/ppmc_reg_S118M_inst/nMRST_i_1;
GLOBAL_PRIMARY_7_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_7_LOADNUM = 0;
; Global primary clock #8
GLOBAL_PRIMARY_8_SIGNALNAME = stm01/ppmc_reg_S118M_inst/nMRST_i_1;
GLOBAL_PRIMARY_8_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_8_LOADNUM = 0;
; Global primary clock #9
GLOBAL_PRIMARY_9_SIGNALNAME = stm11/ppmc_reg_S118M_inst/nMRST_i_1;
GLOBAL_PRIMARY_9_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_9_LOADNUM = 0;
; Global primary clock #10
GLOBAL_PRIMARY_10_SIGNALNAME = stm08/ppmc_reg_S118M_inst/nMRST_i_1;
GLOBAL_PRIMARY_10_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_10_LOADNUM = 0;
; Global primary clock #11
GLOBAL_PRIMARY_11_SIGNALNAME = stm06/ppmc_reg_S118M_inst/nMRST_i_1;
GLOBAL_PRIMARY_11_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_11_LOADNUM = 0;
; Global primary clock #12
GLOBAL_PRIMARY_12_SIGNALNAME = gpio02/LOAD_L_i_i_a2;
GLOBAL_PRIMARY_12_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_12_LOADNUM = 0;
; Global primary clock #13
GLOBAL_PRIMARY_13_SIGNALNAME = gpio01/LOAD_L_i_i_a2_0;
GLOBAL_PRIMARY_13_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_13_LOADNUM = 0;
; Global primary clock #14
GLOBAL_PRIMARY_14_SIGNALNAME = gpio01/LATCH_L_i_i_a2_0;
GLOBAL_PRIMARY_14_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_14_LOADNUM = 0;
; Global primary clock #15
GLOBAL_PRIMARY_15_SIGNALNAME = LATCH_L_i_i_a2;
GLOBAL_PRIMARY_15_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_15_LOADNUM = 0;
; I/O Bank 0 Usage
BANK_0_USED = 20;
BANK_0_AVAIL = 24;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
BANK_0_VREF2 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 22;
BANK_1_AVAIL = 32;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
BANK_1_VREF2 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 19;
BANK_2_AVAIL = 32;
BANK_2_VCCIO = 3.3V;
BANK_2_VREF1 = NA;
BANK_2_VREF2 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 21;
BANK_3_AVAIL = 32;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
BANK_3_VREF2 = NA;
; I/O Bank 6 Usage
BANK_6_USED = 19;
BANK_6_AVAIL = 32;
BANK_6_VCCIO = 3.3V;
BANK_6_VREF1 = NA;
BANK_6_VREF2 = NA;
; I/O Bank 7 Usage
BANK_7_USED = 26;
BANK_7_AVAIL = 32;
BANK_7_VCCIO = 3.3V;
BANK_7_VREF1 = NA;
BANK_7_VREF2 = NA;
; I/O Bank 8 Usage
BANK_8_USED = 0;
BANK_8_AVAIL = 13;
BANK_8_VCCIO = NA;
BANK_8_VREF1 = NA;
BANK_8_VREF2 = NA;
