#----------------------------------------------------------------------
# AutoConstraint_SP0557.sdc
#
# WARNING: This file was auto-generated by Synplify with INCORRECT
#          clock periods and SEPARATE clock groups, which caused
#          S3IO communication errors at high LE utilization.
#
# All constraints are now intentionally DISABLED.
# Correct clock definitions are in:
#   - pll_gen.fdc (PLL module-level, same clock group "pll_clks")
#   - SP0557.fdc  (cross-domain multicycle/false path constraints)
#
# To prevent Synplify from regenerating this file with wrong values,
# set_option -frequency is changed from "auto" to explicit in the
# project file (SP0557_syn.prj).
#
# Date: 2026-02-27
#----------------------------------------------------------------------

# Original auto-generated constraints REMOVED:
# (They had wrong periods: 20MHz as 6.2ns, 100MHz as 3.5ns, 10MHz as 428ns)
# (They used separate clock groups: Autoconstr_clkgroup_0..4)
